// Generated by CoffeeScript 1.6.3
(function() {
  define(["config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/renderer", "config/marionette/application", "config/marionette/view", "config/marionette/nesting", "config/marionette/region/dialog"], function() {});

}).call(this);

/*
//@ sourceMappingURL=_base.map
*/
