// Generated by CoffeeScript 1.6.3
(function() {
  define(["marionette", "apps/header/list/controller", "app", "entities/header"], function(Marionette, Controller, App) {
    var API;
    API = {
      listHeader: function() {
        return Controller.listHeader();
      }
    };
    return App.commands.setHandler("header:list", function() {
      return API.listHeader();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
