// Generated by CoffeeScript 1.6.3
(function() {
  define(["marionette", "apps/footer/show/controller", "app"], function(Marionette, Controller, App) {
    var API;
    API = {
      showFooter: function() {
        return Controller.showFooter();
      }
    };
    return App.commands.setHandler("footer:show", function() {
      return API.showFooter();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
