// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "apps/footer/show/views"], function(App, Show) {
    return {
      showFooter: function() {
        var footerView;
        footerView = this.getFooterView();
        return App.footerRegion.show(footerView);
      },
      getFooterView: function() {
        return new Show.Footer;
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=controller.map
*/
