// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      show_footer: require("text!apps/footer/show/templates/show_footer.htm")
    };
  });

}).call(this);

/*
//@ sourceMappingURL=templates.map
*/
