// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'views/_base', "apps/footer/show/templates"], function(_, AppViews, Templates) {
    var Footer, _ref;
    return {
      Footer: Footer = (function(_super) {
        __extends(Footer, _super);

        function Footer() {
          _ref = Footer.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Footer.prototype.template = _.template(Templates.show_footer);

        return Footer;

      })(AppViews.ItemView)
    };
  });

}).call(this);

/*
//@ sourceMappingURL=views.map
*/
