// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseURL: 'assetsAMD/js',
    paths: {
      jquery: "../../components/jquery/jquery",
      underscore: "../../components/underscore-amd/underscore",
      backbone: "../../components/backbone-amd/backbone",
      "backbone.wreqr": "../../components/backbone.wreqr/lib/amd/backbone.wreqr",
      "backbone.eventbinder": "../../components/backbone.eventbinder/lib/amd/backbone.eventbinder",
      "backbone.babysitter": "../../components/backbone.babysitter/lib/amd/backbone.babysitter",
      marionette: "../../components/marionette/lib/core/amd/backbone.marionette",
      bsModal: "../../components/bootstrap/docs/assets/js/bootstrap-modal",
      text: "../../components/requirejs-text/text"
    },
    shim: {
      bsModal: ["jquery"]
    }
  }, require(["config/_base", "app", "apps/footer/app", "apps/header/app", "apps/rachas/app"], function(_config, App) {
    return App.start();
  }));

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
