// Generated by CoffeeScript 1.6.3
(function() {
  define(["marionette", "backbone"], function(Marionette, Backbone) {
    return _.extend(Marionette.Application.prototype, {
      navigate: function(route, options) {
        if (options == null) {
          options = {};
        }
        console.log(route);
        if (route.charAt(0) === "/") {
          route = "#" + route;
        }
        return Backbone.history.navigate(route, options);
      },
      getCurrentRoute: function() {
        return Backbone.history.fragment;
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=application.map
*/
