// Generated by CoffeeScript 1.6.3
(function() {
  define(["backbone"], function(Backbone) {
    return Backbone.Model.prototype.nestCollection = function(attributeName, nestedCollection) {
      var i, item, _i, _len,
        _this = this;
      console.log('dede');
      for (i = _i = 0, _len = nestedCollection.length; _i < _len; i = ++_i) {
        item = nestedCollection[i];
        this.attributes[attributeName][i] = nestedCollection.at(i).attributes;
      }
      nestedCollection.bind('add', function(initiative) {
        if (!_this.get(attributeName)) {
          _this.attributes[attributeName] = [];
        }
        return _this.get(attributeName).push(initiative.attributes);
      });
      nestedCollection.bind('remove', function(initiative) {
        var updateObj;
        updateObj = {};
        updateObj[attributeName] = _.without(_this.get(attributeName), initiative.attributes);
        return _this.set(updateObj);
      });
      return nestedCollection;
    };
  });

}).call(this);

/*
//@ sourceMappingURL=nesting.map
*/
