// Generated by CoffeeScript 1.6.3
(function() {
  define(["marionette"], function(Marionette) {
    return Marionette.Renderer.render = function(template, data) {
      var path;
      path = template;
      if (!path) {
        throw "Template " + template + " not found!";
      }
      return path(data);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=renderer.map
*/
