// Generated by CoffeeScript 1.6.3
(function() {
  define(["app", "apps/header/list/views"], function(App, Views) {
    return {
      listHeader: function() {
        var headerView, links;
        links = App.request("header:entities");
        headerView = this.getHeaderView(links);
        return App.headerRegion.show(headerView);
      },
      getHeaderView: function(links) {
        return new Views.Headers({
          collection: links
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=controller.map
*/
