// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      headers: require("text!apps/header/list/templates/headers.htm"),
      _header: require("text!apps/header/list/templates/_header.htm")
    };
  });

}).call(this);

/*
//@ sourceMappingURL=templates.map
*/
