// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'views/_base', "apps/header/list/templates"], function(_, AppViews, Templates) {
    var Header, Headers, _ref, _ref1;
    return {
      Header: Header = (function(_super) {
        __extends(Header, _super);

        function Header() {
          _ref = Header.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Header.prototype.template = _.template(Templates._header);

        Header.prototype.tagName = "li";

        return Header;

      })(AppViews.ItemView),
      Headers: Headers = (function(_super) {
        __extends(Headers, _super);

        function Headers() {
          _ref1 = Headers.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        Headers.prototype.template = _.template(Templates.headers);

        Headers.prototype.id = "headerList";

        Headers.prototype.itemView = Header;

        Headers.prototype.itemViewContainer = "ul";

        return Headers;

      })(AppViews.CompositeView)
    };
  });

}).call(this);

/*
//@ sourceMappingURL=views.map
*/
