// Generated by CoffeeScript 1.6.3
(function() {
  define(["msgbus", "apps/book/list/views"], function(msgBus, Views) {
    return {
      listBooks: function(books) {
        var _this = this;
        this.layout = this.getLayout();
        this.layout.on("show", function() {
          _this.showSearchBar();
          return _this.showBookList(books);
        });
        return msgBus.events.trigger("app:show", this.layout);
      },
      showBookDetail: function(book) {
        var view;
        console.log("controller>> showBookDetail");
        view = this.getDetailView(book);
        view.on("dialog:button:clicked", function() {
          return console.log("editView instance dialog:button:clicked");
        });
        return msgBus.events.trigger("app:show:modal", view);
      },
      getDetailView: function(book) {
        return new Views.BookDetailView({
          model: book
        });
      },
      showBookList: function(items) {
        var bookListView;
        bookListView = this.getBookListView(items);
        return this.layout.books.show(bookListView);
      },
      getBookListView: function(items) {
        return new Views.BookList({
          collection: items
        });
      },
      showSearchBar: function() {
        var searchView;
        searchView = this.getSearchView();
        return this.layout.search.attachView(searchView);
      },
      getSearchView: function() {
        return new Views.Search;
      },
      getLayout: function() {
        return new Views.Layout;
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=controller.map
*/
