// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "app"], function(Backbone, App) {
    var API, Header, HeaderCollection, _ref, _ref1;
    Header = (function(_super) {
      __extends(Header, _super);

      function Header() {
        _ref = Header.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      return Header;

    })(Backbone.Model);
    HeaderCollection = (function(_super) {
      __extends(HeaderCollection, _super);

      function HeaderCollection() {
        _ref1 = HeaderCollection.__super__.constructor.apply(this, arguments);
        return _ref1;
      }

      HeaderCollection.prototype.model = Header;

      return HeaderCollection;

    })(Backbone.Collection);
    App.reqres.setHandler("header:entities", function() {
      return API.getHeaderEntities();
    });
    return API = {
      getHeaderEntities: function() {
        var headers;
        return headers = new HeaderCollection([
          {
            name: "Primera",
            url: "/rachas/1"
          }, {
            name: "Segunda",
            url: "/rachas/2"
          }
        ]);
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=header.map
*/
