// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'apps/book/detail/templates', 'views/_base', 'msgbus'], function(_, Templates, AppViews, msgbus) {
    var BookDetailView, _ref;
    return {
      BookDetail: BookDetailView = (function(_super) {
        __extends(BookDetailView, _super);

        function BookDetailView() {
          _ref = BookDetailView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        BookDetailView.prototype.template = _.template(Templates.bookdetail);

        BookDetailView.prototype.modelEvents = {
          "change:name": function() {
            return console.log("name changed");
          }
        };

        return BookDetailView;

      })(AppViews.ItemView)
    };
  });

  ({
    events: {
      "click #close-dialog": function() {
        return this.trigger("dialog:close");
      }
    },
    dialog: {
      title: "Edit Event",
      className: "dialogClass",
      buttons: false
    },
    onClose: function() {
      return console.log("view closing");
    },
    onDialogButtonClicked: function() {
      return console.log("dialog method onDialogButtonClicked");
    }
  });

}).call(this);

/*
//@ sourceMappingURL=views.map
*/
