// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette", "apps/rachas/list/controller", "app", "entities/racha"], function(Marionette, Controller, App) {
    var API, Router, _ref;
    Router = (function(_super) {
      __extends(Router, _super);

      function Router() {
        _ref = Router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Router.prototype.appRoutes = {
        "rachas": "listRachas",
        "rachas/:id": "showRacha"
      };

      return Router;

    })(Marionette.AppRouter);
    App.addInitializer(function() {
      return new Router({
        controller: API
      });
    });
    return API = {
      listRachas: function() {
        return Controller.listRachas();
      },
      showRacha: function(id) {
        return Controller.listRachas(id);
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
