// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette"], function(Marionette) {
    var CollectionView, CompositeView, ItemView, Layout, _ref, _ref1, _ref2, _ref3;
    return {
      CollectionView: CollectionView = (function(_super) {
        __extends(CollectionView, _super);

        function CollectionView() {
          _ref = CollectionView.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        return CollectionView;

      })(Marionette.CollectionView),
      CompositeView: CompositeView = (function(_super) {
        __extends(CompositeView, _super);

        function CompositeView() {
          _ref1 = CompositeView.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        return CompositeView;

      })(Marionette.CompositeView),
      ItemView: ItemView = (function(_super) {
        __extends(ItemView, _super);

        function ItemView() {
          _ref2 = ItemView.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        return ItemView;

      })(Marionette.ItemView),
      Layout: Layout = (function(_super) {
        __extends(Layout, _super);

        function Layout() {
          _ref3 = Layout.__super__.constructor.apply(this, arguments);
          return _ref3;
        }

        return Layout;

      })(Marionette.Layout)
    };
  });

}).call(this);

/*
//@ sourceMappingURL=_base.map
*/
